version: '2'

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=data_base
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret 
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  web:
    build: ./test-project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test-project:/test-project
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true